import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    ignores: [
      // Generated by Next.js — never edit, never lint.
      "next-env.d.ts",
      "node_modules/**",
      ".next/**",
      "out/**",
      "dist/**",
      "desktop/dist/**",
      "desktop/release/**",
      "desktop/resources/server/**",
      "desktop/node_modules/**",
      "data/**",
      "*.log",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // The codebase marks deliberately-unused parameters with a leading `_`
    // (callback signatures, interface implementations) and uses rest-sibling
    // destructuring (`const { secret: _s, ...pub } = rec`) to strip fields.
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
    },
  },
];

export default eslintConfig;
