import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    ignores: [
      // Generated by Next.js — never edit, never lint.
      "next-env.d.ts",
      "node_modules/**",
      ".next/**",
      "out/**",
      "dist/**",
      "desktop/dist/**",
      "desktop/release/**",
      "desktop/resources/server/**",
      "desktop/node_modules/**",
      "data/**",
      "*.log",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;
