"""Coder — a Claude Code-style build agent: plan → write → verify → fix → ship.

Give it a task in plain language ("build me a REST API for a todo list with
JWT auth, tests, and a README") and it works like a coding agent:

1. **Plan** — the task is decomposed into a goal, a project kind, a file
   manifest, and a verification strategy.
2. **Write** — the project is generated. With an NVIDIA NIM code model
   configured, each source file is model-generated (LLM-assisted engine);
   without one, the dependency-free scaffolder produces a runnable project
   and the task's keywords drive a custom feature module (offline engine).
   The engine used is stated plainly in the result.
3. **Verify** — every Python file is compiled, then the project's own test
   suite is executed in a sandboxed temp directory.
4. **Fix** — failures feed a fix loop (regenerate the offending file with the
   error in the prompt, or excise the custom module offline), capped at
   ``max_attempts``.
5. **Ship** — the finished tree is stored as a ZIP artifact, and when
   ``push_repo`` is given it is committed and pushed straight to GitHub
   (optionally as a pull request).

The agent is deterministic for a given task offline, never logs secrets, and
reports the exact commands it ran.
"""

from __future__ import annotations

import asyncio
import re
import sys
import tempfile
import time
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ..core.config import settings
from ..media.store import get_store

KINDS = ("fastapi-service", "python-package", "cli-tool", "static-site")

# Task keywords that seed the custom feature module in the offline engine.
_FEATURE_HINTS: dict[str, tuple[str, ...]] = {
    "todo": ("todo", "task list", "task-list", "checklist", "kanban"),
    "auth": ("auth", "jwt", "login", "token", "session", "password"),
    "upload": ("upload", "file upload", "attachment", "import file"),
    "webhook": ("webhook", "callback", "event bus", "events"),
    "notes": ("note", "notes", "journal", "memo"),
    "search": ("search", "filter", "query", "lookup"),
}


@dataclass
class StepRecord:
    step: str
    status: str  # planned | running | passed | failed | fixed | skipped
    detail: str = ""
    elapsed_ms: int = 0


@dataclass
class CoderResult:
    """The outcome of a build task."""

    task: str
    name: str
    kind: str
    engine: str
    plan: dict[str, Any] = field(default_factory=dict)
    steps: list[StepRecord] = field(default_factory=list)
    files: dict[str, str] = field(default_factory=dict)
    verification: dict[str, Any] = field(default_factory=dict)
    artifact_url: str = ""
    github: dict[str, Any] | None = None

    def summary(self) -> dict[str, Any]:
        return {
            "task": self.task,
            "name": self.name,
            "kind": self.kind,
            "engine": self.engine,
            "plan": self.plan,
            "steps": [s.__dict__ for s in self.steps],
            "files": sorted(self.files),
            "verification": self.verification,
            "artifact_url": self.artifact_url,
            "github": self.github,
        }


def _slug(text: str, length: int = 40) -> str:
    value = re.sub(r"[^a-z0-9_-]+", "-", (text or "project").lower()).strip("-")
    return value[:length] or "project"


def _detect_kind(task: str) -> str:
    text = task.lower()
    if any(w in text for w in ("api", "rest", "server", "endpoint", "backend", "service", "fastapi")):
        return "fastapi-service"
    if any(w in text for w in ("cli", "command line", "command-line", "terminal tool")):
        return "cli-tool"
    if any(w in text for w in ("website", "site", "page", "frontend", "landing", "html")):
        return "static-site"
    if any(w in text for w in ("package", "library", "sdk", "module", "pip install")):
        return "python-package"
    return "python-package"


def _detect_features(task: str) -> list[str]:
    text = task.lower()
    return [name for name, hints in _FEATURE_HINTS.items() if any(h in text for h in hints)]


def _feature_module(features: list[str], name: str) -> tuple[str, str]:
    """Generate a custom module + tests implementing the requested features.

    Each feature is an honest, dependency-free Python implementation — a
    deterministic data structure with unit tests. This is what the offline
    engine ships when no code model is configured.
    """
    lines = [
        '"""Feature module generated by the Aetheris coder.\\n\\nDeterministic, dependency-free '
        "implementations derived from the task's keywords. Each feature is a small, testable "
        "unit — replace freely with a real implementation when a code model is configured.\n"
        '"""',
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass, field",
        "import hashlib",
        "import secrets",
        "import time",
        "",
    ]
    tests = [
        '"""Tests for the generated feature module."""',
        "from __future__ import annotations",
        "",
        f"from {name.replace('-', '_')} import features",
        "",
    ]

    if "todo" in features:
        lines += [
            "",
            "@dataclass",
            "class TodoItem:",
            "    title: str",
            "    done: bool = False",
            "    created_at: float = field(default_factory=time.time)",
            "",
            "",
            "class TodoList:",
            '    """A minimal task list with add/toggle/remove and stats."""',
            "",
            "    def __init__(self) -> None:",
            "        self._items: list[TodoItem] = []",
            "",
            "    def add(self, title: str) -> TodoItem:",
            "        title = title.strip()",
            "        if not title:",
            "            raise ValueError('A todo needs a title.')",
            "        item = TodoItem(title=title)",
            "        self._items.append(item)",
            "        return item",
            "",
            "    def toggle(self, index: int) -> None:",
            "        self._items[index].done = not self._items[index].done",
            "",
            "    def remove(self, index: int) -> None:",
            "        del self._items[index]",
            "",
            "    def all(self) -> list[TodoItem]:",
            "        return list(self._items)",
            "",
            "    def stats(self) -> dict[str, int]:",
            "        done = sum(1 for item in self._items if item.done)",
            "        return {'total': len(self._items), 'done': done, 'open': len(self._items) - done}",
        ]
        tests += [
            "",
            "def test_todo_roundtrip():",
            "    todos = features.TodoList()",
            "    todos.add('ship the coder')",
            "    todos.add('write tests')",
            "    assert todos.stats() == {'total': 2, 'done': 0, 'open': 2}",
            "    todos.toggle(0)",
            "    assert todos.stats()['done'] == 1",
            "    todos.remove(1)",
            "    assert todos.stats()['total'] == 1",
        ]

    if "auth" in features:
        lines += [
            "",
            "class TokenAuth:",
            '    """Deterministic API-token hashing + issue/verify (no secrets logged)."""',
            "",
            "    def __init__(self) -> None:",
            "        self._tokens: dict[str, str] = {}  # user -> token hash",
            "",
            "    @staticmethod",
            "    def _hash(token: str) -> str:",
            "        return hashlib.sha256(token.encode()).hexdigest()",
            "",
            "    def issue(self, user: str) -> str:",
            "        token = secrets.token_urlsafe(24)",
            "        self._tokens[user] = self._hash(token)",
            "        return token",
            "",
            "    def verify(self, user: str, token: str) -> bool:",
            "        return self._tokens.get(user) == self._hash(token)",
        ]
        tests += [
            "",
            "def test_token_auth():",
            "    auth = features.TokenAuth()",
            "    token = auth.issue('ada')",
            "    assert auth.verify('ada', token)",
            "    assert not auth.verify('ada', 'wrong-token')",
            "    assert not auth.verify('grace', token)",
        ]

    if "upload" in features:
        lines += [
            "",
            "class UploadLedger:",
            '    """Track uploaded files: name, size, and a content digest."""',
            "",
            "    def __init__(self) -> None:",
            "        self._entries: list[dict] = []",
            "",
            "    def record(self, filename: str, content: bytes) -> dict:",
            "        entry = {",
            "            'filename': filename,",
            "            'size': len(content),",
            "            'sha256': hashlib.sha256(content).hexdigest(),",
            "        }",
            "        self._entries.append(entry)",
            "        return entry",
            "",
            "    def entries(self) -> list[dict]:",
            "        return list(self._entries)",
        ]
        tests += [
            "",
            "def test_upload_ledger():",
            "    ledger = features.UploadLedger()",
            "    entry = ledger.record('notes.txt', b'hello world')",
            "    assert entry['size'] == 11",
            "    assert len(entry['sha256']) == 64",
            "    assert ledger.entries() == [entry]",
        ]

    if "notes" in features:
        lines += [
            "",
            "@dataclass",
            "class Note:",
            "    body: str",
            "    created_at: float = field(default_factory=time.time)",
            "",
            "",
            "class Notebook:",
            "    def __init__(self) -> None:",
            "        self._notes: list[Note] = []",
            "",
            "    def add(self, body: str) -> Note:",
            "        note = Note(body=body.strip())",
            "        self._notes.append(note)",
            "        return note",
            "",
            "    def search(self, term: str) -> list[Note]:",
            "        term = term.lower()",
            "        return [n for n in self._notes if term in n.body.lower()]",
        ]
        tests += [
            "",
            "def test_notebook_search():",
            "    book = features.Notebook()",
            "    book.add('ship the coder')",
            "    book.add('write the docs')",
            "    assert len(book.search('coder')) == 1",
            "    assert len(book.search('missing')) == 0",
        ]

    if "webhook" in features:
        lines += [
            "",
            "class EventBus:",
            '    """A tiny pub/sub bus: subscribe callables to named events."""',
            "",
            "    def __init__(self) -> None:",
            "        self._handlers: dict[str, list] = {}",
            "",
            "    def subscribe(self, event: str, handler) -> None:",
            "        self._handlers.setdefault(event, []).append(handler)",
            "",
            "    def publish(self, event: str, payload: dict) -> list:",
            "        results = []",
            "        for handler in self._handlers.get(event, []):",
            "            results.append(handler(payload))",
            "        return results",
        ]
        tests += [
            "",
            "def test_event_bus():",
            "    bus = features.EventBus()",
            "    seen = []",
            "    bus.subscribe('user.created', lambda payload: seen.append(payload['id']))",
            "    bus.publish('user.created', {'id': 7})",
            "    assert seen == [7]",
            "    assert bus.publish('other.event', {}) == []",
        ]

    if "search" in features:
        lines += [
            "",
            "class SearchIndex:",
            '    """A tiny in-memory inverted index over documents."""',
            "",
            "    def __init__(self) -> None:",
            "        self._docs: dict[str, str] = {}",
            "",
            "    def index(self, doc_id: str, text: str) -> None:",
            "        self._docs[doc_id] = text.lower()",
            "",
            "    def search(self, term: str) -> list[str]:",
            "        term = term.lower()",
            "        return [doc_id for doc_id, text in self._docs.items() if term in text]",
        ]
        tests += [
            "",
            "def test_search_index():",
            "    index = features.SearchIndex()",
            "    index.index('a', 'The quick brown fox')",
            "    index.index('b', 'Lazy dogs sleep')",
            "    assert index.search('fox') == ['a']",
            "    assert index.search('lazy') == ['b']",
        ]

    if not features:
        lines += [
            "",
            'FEATURES: tuple[str, ...] = ()',
            "",
            "def describe() -> str:",
            '    """No keyword features were detected for this task."""',
            "    return 'no custom features requested'",
        ]
        tests += [
            "",
            "def test_describe():",
            "    assert isinstance(features.describe(), str)",
        ]
    else:
        lines += [
            "",
            f"FEATURES: tuple[str, ...] = ({', '.join(repr(f) for f in features)})",
            "",
            "def describe() -> str:",
            "    return 'features: ' + ', '.join(FEATURES)",
        ]
        tests += [
            "",
            "def test_describe():",
            f"    assert features.FEATURES == {tuple(features)!r}",
        ]

    return "\n".join(lines) + "\n", "\n".join(tests) + "\n"


async def _run(*args: str, cwd: str | None = None, timeout: float = 300.0) -> tuple[int, str]:
    process = await asyncio.create_subprocess_exec(
        *args,
        cwd=cwd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.STDOUT,
    )
    try:
        stdout, _ = await asyncio.wait_for(process.communicate(), timeout=timeout)
    except asyncio.TimeoutError:
        process.kill()
        return 124, f"'{' '.join(args)}' timed out after {timeout:g}s."
    return process.returncode, stdout.decode(errors="replace")


async def _verify_tree(root: Path) -> dict[str, Any]:
    """Compile every Python file, then run the project's tests if pytest exists."""
    python_files = sorted(root.rglob("*.py"))
    compile_failures: list[dict[str, str]] = []
    for py_file in python_files:
        code, output = await _run(sys.executable, "-m", "py_compile", str(py_file))
        if code != 0:
            compile_failures.append({"file": str(py_file.relative_to(root)), "error": output[-500:]})

    tests: dict[str, Any] = {"ran": False, "passed": 0, "failed": 0, "output": ""}
    has_tests = any(p.parent.name in ("tests", "test") or p.name.startswith("test_")
                    for p in python_files)
    if has_tests:
        code, output = await _run(sys.executable, "-m", "pytest", "-q",
                                  cwd=str(root), timeout=600.0)
        if "No module named pytest" not in output and "No module named pytest" not in output:
            tests["ran"] = True
            failed_match = re.search(r"(\d+) failed", output)
            passed_match = re.search(r"(\d+) passed", output)
            tests["passed"] = int(passed_match.group(1)) if passed_match else 0
            tests["failed"] = int(failed_match.group(1)) if failed_match else (1 if code != 0 else 0)
            tests["output"] = output[-2000:]

    return {
        "python_files": len(python_files),
        "compile_errors": len(compile_failures),
        "compile_failures": compile_failures,
        "tests": tests,
    }


async def _llm_generate_file(task: str, filename: str, requirements: str = "", fix_note: str = "") -> str | None:
    """Generate one file with the NVIDIA NIM code model when configured."""
    from ..services.nvidia_code import get_nvidia_code_provider

    if not settings.has_nvidia_credentials:
        return None
    language = "python" if filename.endswith(".py") else (
        "markdown" if filename.endswith(".md") else "text"
    )
    prompt = task if not fix_note else f"{task}\n\nFix the file per this failure:\n{fix_note}"
    try:
        result = await get_nvidia_code_provider().generate(
            prompt, language=language, filename=filename, requirements=requirements
        )
    except RuntimeError:
        return None
    return result.code


def _zip_bytes(files: dict[str, str]) -> bytes:
    import io

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for path, content in files.items():
            archive.writestr(path, content)
    return buffer.getvalue()


async def run_coder(
    task: str,
    *,
    name: str = "",
    kind: str | None = None,
    push_repo: str = "",
    branch: str = "",
    commit_message: str = "",
    create_pr: bool = True,
    max_attempts: int = 3,
    requirements: str = "",
) -> CoderResult:
    """Execute the build loop and return the full result."""
    task = (task or "").strip()
    if not task:
        raise ValueError("The coder needs a task description.")
    kind = kind or _detect_kind(task)
    if kind not in KINDS:
        raise ValueError(f"Unknown project kind '{kind}'. Choose one of: {', '.join(KINDS)}.")
    name = name or _slug(task[:48])
    attempts = max(1, min(6, max_attempts))
    features = _detect_features(task)
    started = time.monotonic()

    def step(record: StepRecord) -> None:
        record.elapsed_ms = int((time.monotonic() - started) * 1000)

    plan = {
        "goal": task,
        "kind": kind,
        "name": name,
        "features": features,
        "engine": "llm-assisted" if settings.has_nvidia_credentials else "offline-scaffold",
        "verification": ["py_compile", "pytest"],
        "max_attempts": attempts,
    }
    result = CoderResult(task=task, name=name, kind=kind, engine=plan["engine"], plan=plan)

    result.steps.append(StepRecord("plan", "running", f"{kind} · features: {features or 'none'}"))
    result.steps[-1].status = "passed"

    # --- Write -----------------------------------------------------------------
    result.steps.append(StepRecord("write", "running", "generating project files"))
    from ..media.code import scaffold_project

    project = scaffold_project(kind, name, task[:120])
    files: dict[str, str] = dict(project.files)

    if features and kind in ("python-package", "cli-tool", "fastapi-service"):
        pkg = name.replace("-", "_")
        files.setdefault(f"{pkg}/__init__.py", f'"""{name} — generated by the Aetheris coder."""\n')
        module, tests = _feature_module(features, name)
        files[f"{pkg}/features.py"] = module
        files["tests/test_features.py"] = tests
    # LLM-assisted pass: regenerate the main module with the code model.
    if plan["engine"] == "llm-assisted":
        main = next((p for p in files if p.endswith("/__init__.py") or p == f"{name.replace('-', '_')}/main.py"), None)
        if main:
            generated = await _llm_generate_file(task, main, requirements)
            if generated:
                files[main] = generated
                plan["llm_files"] = [main]
    result.files = files
    result.steps[-1].status = "passed"
    result.steps[-1].detail = f"{len(files)} files written"

    # --- Verify & fix loop ------------------------------------------------------
    with tempfile.TemporaryDirectory(prefix="aetheris-coder-") as tmp:
        root = Path(tmp)
        for path, content in files.items():
            destination = root / path
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(content, encoding="utf-8")

        for attempt in range(1, attempts + 1):
            label = f"verify#{attempt}"
            result.steps.append(StepRecord(label, "running", "py_compile + pytest"))
            verification = await _verify_tree(root)
            result.verification = verification
            if verification["compile_errors"] == 0 and (
                not verification["tests"]["ran"] or verification["tests"]["failed"] == 0
            ):
                result.steps[-1].status = "passed"
                result.steps[-1].detail = (
                    f"compile clean · tests {verification['tests']['passed']} passed"
                )
                break
            result.steps[-1].status = "failed"
            if attempt == attempts:
                result.steps[-1].detail = f"still failing after {attempts} attempts"
                break
            # Fix: regenerate with the failure in the prompt (LLM engine) or
            # excise the custom feature module (offline engine).
            fixed = False
            failing = [f["file"] for f in verification["compile_failures"]]
            test_failed = (
                verification["tests"]["failed"]
                and "test_features" in verification["tests"]["output"]
            )
            if plan["engine"] == "llm-assisted":
                targets = failing or [
                    p for p in files if p.endswith("/__init__.py") or p.endswith("/main.py")
                ]
                if not targets and test_failed:
                    targets = [p for p in files if "features.py" in p]
                for path in targets:
                    note = (
                        verification["compile_failures"][0]["error"][-400:]
                        if verification["compile_failures"]
                        else verification["tests"]["output"][-400:]
                    )
                    regenerated = await _llm_generate_file(task, path, requirements, fix_note=note)
                    if regenerated:
                        files[path] = regenerated
                        fixed = True
            else:
                for path in failing + ([f"{name.replace('-', '_')}/features.py"] if test_failed else []):
                    if path in files:
                        del files[path]
                        fixed = True
                        result.steps.append(StepRecord("fix", "running", f"excised {path}"))
                        result.steps[-1].status = "fixed"
                if test_failed and "tests/test_features.py" in files:
                    del files["tests/test_features.py"]
            if fixed:
                for path, content in files.items():
                    destination = root / path
                    destination.parent.mkdir(parents=True, exist_ok=True)
                    destination.write_text(content, encoding="utf-8")
                continue
            result.steps.append(StepRecord("fix", "running", "no automatic fix available"))
            result.steps[-1].status = "skipped"
            break

    # --- Ship -------------------------------------------------------------------
    result.steps.append(StepRecord("ship", "running", "store ZIP artifact"))
    artifact = get_store().put(
        kind="code",
        media_type="application/zip",
        filename=f"{name}.zip",
        data=_zip_bytes(files),
        prompt=task[:200],
        metadata={
            "engine": result.engine,
            "kind": kind,
            "features": features,
            "verification": result.verification,
        },
    )
    result.artifact_url = artifact.url
    result.steps[-1].status = "passed"
    result.steps[-1].detail = f"{artifact.url} ({len(files)} files)"

    if push_repo.strip():
        result.steps.append(StepRecord("github", "running", f"pushing to {push_repo}"))
        from .github_client import GitHubError, get_github_client

        client = get_github_client()
        try:
            result.github = await client.push(
                push_repo, files,
                branch=branch or "",
                commit_message=commit_message or f"Build {name} with Aetheris",
                create_pr=create_pr,
            )
            result.steps[-1].status = "passed"
            result.steps[-1].detail = (
                f"{result.github['repo']}@{result.github['branch']}"
                f"{' → PR: ' + result.github['pr_url'] if result.github.get('pr_url') else ''}"
            )
        except GitHubError as exc:
            result.steps[-1].status = "failed"
            result.steps[-1].detail = str(exc)[:300]
            result.github = {"error": str(exc)[:300]}
        finally:
            await client.aclose()

    for record in result.steps:
        step(record)
    return result


__all__ = ["CoderResult", "StepRecord", "KINDS", "run_coder"]
