/**
 * The two capabilities that used to need a binary from a host we cannot reach:
 *   - executing a page's own JavaScript  → jsdom, in-process
 *   - sampling video frames              → ffmpeg compiled to WebAssembly, in a worker thread
 *
 * Neither test touches the network. The video fixture is a real H.264 MP4 (13 KB) generated by the
 * WASM core itself — see tools/gen-fixture.ts.
 */
import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

process.env.AETHERIS_DATA_DIR = mkdtempSync(path.join(tmpdir(), "aeth-jseng-"));

import { browserStatus, jsdomAvailable, renderWithJsdom, snapshot, subresourceAllowed } from "../src/core/browser/agent";
import { sampleFramesWithWasm, wasmFfmpegAvailable, wasmFfmpegVersion } from "../src/core/multimodal/wasmffmpeg";

const FIXTURE = path.join(__dirname, "fixtures", "sample.mp4");

// ---------------------------------------------------------------- page JavaScript (jsdom) --------

test("jsdom executes page JavaScript, so a client-rendered page yields real text", async () => {
  assert.equal(jsdomAvailable(), true, "jsdom should be installed");
  const html = `<!doctype html><html><head><title>Shell</title></head><body><div id="root"></div>
<script>
  // Built by concatenation so neither marker appears literally in the source below.
  document.title = ["Rendered", "by JS"].join(" ");
  document.getElementById("root").innerHTML =
    "<h1>Plans</h1><ul><li>Free $" + 0 + "</li><li>Pro $" + 19 + "</li></ul>";
</script></body></html>`;
  // The words below exist nowhere in the source markup; only running the script can produce them.
  assert.doesNotMatch(html, /Rendered by JS/);
  assert.doesNotMatch(html, /Pro \$19/);

  const out = await renderWithJsdom(html, "https://example.com/pricing");
  assert.equal(out.ok, true, `render failed: ${out.reason}`);
  assert.match(out.html, /<title>Rendered by JS<\/title>/, `title not set by script:\n${out.html.slice(0, 300)}`);
  assert.match(out.html, /Pro \$19/, `list not built by script:\n${out.html.slice(0, 300)}`);

  // And the text the agent would read is the rendered content, not the empty shell.
  const snap = snapshot(out.url, out.html, 200);
  assert.match(snap.text, /Plans/);
  assert.match(snap.text, /Pro \$19/);
});

test("jsdom waits for asynchronous rendering instead of serialising too early", async () => {
  const html = `<!doctype html><html><body><p id="s">loading</p>
<script>setTimeout(function () { document.getElementById("s").textContent = "arrived after 50ms"; }, 50);</script>
</body></html>`;
  const out = await renderWithJsdom(html, "https://example.com/", { settleMs: 300 });
  assert.equal(out.ok, true, `render failed: ${out.reason}`);
  assert.match(out.html, /arrived after 50ms/, `timer had not run yet:\n${out.html.slice(0, 300)}`);
  assert.doesNotMatch(out.html, />loading</, "the placeholder survived, so we serialised before the timer");
});

test("a shell stops being reported as needsJs once its scripts have run", async () => {
  const shell = `<!doctype html><html><head></head><body><div id="app"></div>
<script src="/static/bundle.js"></script>
<script>document.getElementById("app").innerHTML =
  "<article><h1>Quarterly report</h1><p>Revenue is up eleven percent.</p></article>";</script>
</body></html>`;
  const before = snapshot("https://example.com/report", shell, 200);
  assert.equal(before.needsJs, true, "the raw shell must be flagged as needing JavaScript");

  const out = await renderWithJsdom(shell, "https://example.com/report");
  assert.equal(out.ok, true, `render failed: ${out.reason}`);
  // jsRan is what JsdomEngine passes: the markup still looks like a shell, but the scripts ran.
  const after = snapshot(out.url, out.html, 200, 12_000, true);
  assert.match(after.text, /Revenue is up eleven percent/, `content missing:\n${after.text.slice(0, 300)}`);
  assert.notEqual(after.needsJs, true, "still flagged as an unrendered shell after the scripts ran");
  assert.equal(after.jsExecuted, true, "the snapshot should record that JavaScript ran");
});

test("jsdom never executes a script that failed to load, and still returns the rest", async () => {
  const html = `<!doctype html><html><body><div id="m">untouched</div>
<script src="https://cdn.invalid-host.example/x.js"></script>
<script>document.getElementById("m").textContent = "inline ran";</script>
</body></html>`;
  const out = await renderWithJsdom(html, "https://example.com/", { settleMs: 200 });
  assert.equal(out.ok, true, `render failed: ${out.reason}`);
  assert.match(out.html, /inline ran/, "an unreachable cross-origin script blocked the inline one");
  assert.doesNotMatch(out.html, /from the cdn/i);
});

test("the subresource gate refuses off-origin and private-range fetches", () => {
  const origin = "https://example.com";
  // Same origin: allowed.
  assert.equal(subresourceAllowed("https://example.com/static/a.js", origin), true);
  // Off origin: refused by default, allowed only when explicitly opted in.
  assert.equal(subresourceAllowed("https://cdn.other.com/a.js", origin), false, "a third-party CDN must be refused by default");
  assert.equal(subresourceAllowed("https://cdn.other.com/a.js", origin, true), true);
  // The SSRF gate holds even with cross-origin allowed — this is the important one.
  assert.equal(subresourceAllowed("http://169.254.169.254/latest/meta-data", origin, true), false, "cloud metadata must never be fetched");
  assert.equal(subresourceAllowed("http://127.0.0.1:3000/x.js", origin, true), false, "loopback must never be fetched");
  assert.equal(subresourceAllowed("http://10.0.0.5/x.js", origin, true), false, "private ranges must never be fetched");
  assert.equal(subresourceAllowed("http://192.168.1.1/admin", origin, true), false, "private ranges must never be fetched");
  assert.equal(subresourceAllowed("not a url", origin, true), false, "an unparseable URL must be refused");
});

test("browserStatus names the engine that will actually be used", async () => {
  const s = await browserStatus();
  assert.equal(s.http.available, true);
  assert.equal(s.jsdom.available, true, "jsdom is a real dependency, so it should report available");
  assert.equal(s.engine, s.playwright.available ? "playwright" : "jsdom", `wrong engine reported: ${s.engine}`);
});

// ------------------------------------------------------- video frame sampling (ffmpeg as WASM) ---

test("ffmpeg-as-WASM samples real JPEG frames with no host binary", async () => {
  assert.equal(wasmFfmpegAvailable(), true, "@ffmpeg/core should be installed from the registry");
  const version = await wasmFfmpegVersion();
  assert.match(String(version), /^\d+\.\d+(\.\d+)?$/, `expected an ffmpeg version, got: ${version}`);

  const buf = readFileSync(FIXTURE);
  assert.equal(buf.subarray(4, 8).toString("latin1"), "ftyp", "the fixture is not an ISO base-media file");

  const r = await sampleFramesWithWasm(buf, "sample.mp4", { everySeconds: 1, maxFrames: 3, width: 160 });
  assert.equal(r.ok, true, `sampling failed: ${r.reason}`);
  assert.equal(r.frames.length, 3, `expected 3 frames, got ${r.frames.length}`);
  for (const [i, f] of r.frames.entries()) {
    assert.equal(f.subarray(0, 3).toString("hex"), "ffd8ff", `frame ${i} is not a JPEG`);
    assert.ok(f.length > 500, `frame ${i} is suspiciously small: ${f.length} bytes`);
  }
  assert.deepEqual(r.atSeconds, [0, 1, 2], "the sample timestamps do not match the requested interval");
});

test("frame sampling degrades to container facts rather than guessing", async () => {
  const empty = await sampleFramesWithWasm(Buffer.alloc(0), "x.mp4");
  assert.equal(empty.ok, false);
  assert.match(String(empty.reason), /empty/i, `unhelpful reason: ${empty.reason}`);

  const buf = readFileSync(FIXTURE);
  const over = await sampleFramesWithWasm(buf, "sample.mp4", { maxInputBytes: 100 });
  assert.equal(over.ok, false);
  assert.match(String(over.reason), /over the .* limit/, `unhelpful reason: ${over.reason}`);
  assert.equal(over.frames.length, 0, "a rejected input must not return frames");
});
