"""Integration tools — the Claude Code-style build agent and GitHub push.

Two tools that turn the toolbelt into a shipping pipeline:

* ``code_agent``     — plan → write → verify → fix → ship a whole project
  from a plain-language task, returning the ZIP artifact URL.
* ``push_to_github`` — push files (or a scaffolded ZIP artifact) straight to
  a GitHub repository, optionally opening a pull request.
"""

from __future__ import annotations

import json
from typing import Any

from ..core.config import settings
from ..media.store import get_store
from .registry import ToolError, register


@register(
    "code_agent",
    (
        "Act as a coding agent: take a plain-language task, plan a project, "
        "generate the files, compile them, run their test suite, fix failures, "
        "and return a downloadable ZIP artifact — optionally pushing the result "
        "to a GitHub repository as a pull request. Works offline (deterministic "
        "scaffold + keyword-derived features) and upgrades to LLM-assisted file "
        "generation when an NVIDIA NIM code model is configured."
    ),
    {
        "type": "object",
        "properties": {
            "task": {"type": "string", "description": "What to build, in plain language."},
            "name": {"type": "string", "description": "Project name (optional; derived from the task)."},
            "kind": {"type": "string", "enum": ["fastapi-service", "python-package", "cli-tool", "static-site"],
                     "description": "Project kind (optional; auto-detected)."},
            "push_repo": {"type": "string", "description": "GitHub repository as owner/name to push to (optional)."},
            "branch": {"type": "string", "description": "Branch to push (optional)."},
            "commit_message": {"type": "string", "description": "Commit message (optional)."},
            "create_pr": {"type": "boolean", "description": "Open a pull request after pushing (default true)."},
        },
        "required": ["task"],
    },
    tags=("creation", "integration"),
)
async def code_agent(
    task: str,
    name: str = "",
    kind: str | None = None,
    push_repo: str = "",
    branch: str = "",
    commit_message: str = "",
    create_pr: bool = True,
) -> str:
    """Build a whole project from a task (plan → write → verify → fix → ship)."""
    if not settings.code_generation_enabled:
        raise ToolError(
            "Code generation is disabled on this deployment. "
            "Set AETHERIS_CODE_GENERATION_ENABLED=true to enable it."
        )
    from ..services.coder import run_coder

    try:
        result = await run_coder(
            task,
            name=name,
            kind=kind,
            push_repo=push_repo,
            branch=branch,
            commit_message=commit_message,
            create_pr=create_pr,
        )
    except (ValueError, RuntimeError) as exc:
        raise ToolError(str(exc)) from exc
    return json.dumps(result.summary(), indent=2)


@register(
    "push_to_github",
    (
        "Push code to GitHub: commit files (or a previously scaffolded ZIP "
        "artifact) to a repository, creating the repository when it does not "
        "exist and optionally opening a pull request. Uses the configured "
        "AETHERIS_GITHUB_TOKEN or the authenticated 'gh' CLI."
    ),
    {
        "type": "object",
        "properties": {
            "repo": {"type": "string", "description": "Repository as owner/name."},
            "files": {"type": "object",
                      "description": "Path → text content map of files to push (optional)."},
            "artifact": {"type": "string",
                         "description": "ZIP artifact id or URL to push (optional)."},
            "commit_message": {"type": "string", "description": "Commit message."},
            "branch": {"type": "string", "description": "Branch to push (optional)."},
            "create_pr": {"type": "boolean", "description": "Open a pull request (default true)."},
        },
        "required": ["repo"],
    },
    tags=("integration",),
)
async def push_to_github(
    repo: str,
    files: dict[str, str] | None = None,
    artifact: str = "",
    commit_message: str = "Generated by Aetheris",
    branch: str = "",
    create_pr: bool = True,
) -> str:
    """Commit and push files to GitHub, optionally as a pull request."""
    if not settings.github_enabled:
        raise ToolError(
            "The GitHub integration is disabled on this deployment. "
            "Set AETHERIS_GITHUB_ENABLED=true to enable it."
        )
    from ..services.github_client import GitHubError, GitHubClient

    payload: dict[str, Any] = dict(files or {})
    if artifact.strip():
        source = artifact.strip()
        if "/" in source:
            source = source.rstrip("/").rsplit("/", 1)[-1]
        original = get_store().get(source)
        if original is None or original.media_type != "application/zip":
            raise ToolError(f"No ZIP artifact '{artifact}'. Scaffold a project first.")
        import io as _io
        import zipfile as _zipfile

        with _zipfile.ZipFile(_io.BytesIO(original.data)) as archive:
            for name in archive.namelist():
                if name.endswith("/"):
                    continue
                try:
                    payload[name] = archive.read(name).decode("utf-8")
                except UnicodeDecodeError:
                    continue
    if not payload:
        raise ToolError("Provide 'files' and/or a ZIP 'artifact' to push.")

    client = GitHubClient()
    try:
        result = await client.push(
            repo, payload,
            branch=branch or "",
            commit_message=commit_message,
            create_pr=create_pr,
        )
    except GitHubError as exc:
        raise ToolError(str(exc)) from exc
    finally:
        await client.aclose()
    return json.dumps(result, indent=2)
