"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { renderMarkdown } from "@/components/markdown";

type Kind = "flashcard" | "mcq" | "cloze" | "short";
interface Srs { ease: number; interval: number; reps: number; lapses: number; due: number; lastReviewed?: number }
interface Card { id: string; kind: Kind; front: string; back: string; options?: string[]; explanation?: string; difficulty: 1 | 2 | 3; tags: string[]; srs: Srs }
interface Stats { total: number; due: number; learned: number; byStage: { new: number; learning: number; young: number; mature: number }; retention: number | null }
interface DeckLite { id: string; title: string; subject: string; scope: string; language: string; agent: string; updatedAt: number; stats: Stats; history: { at: number; reviewed: number; correct: number }[] }
interface Deck extends Omit<DeckLite, "stats" | "history"> { cards: Card[]; history: { at: number; reviewed: number; correct: number }[] }
interface AgentLite { id: string; name: string; icon: string }

const KIND_LABEL: Record<Kind, string> = { flashcard: "Flashcard", mcq: "Multiple choice", cloze: "Fill the blank", short: "Short answer" };
const clozeFront = (s: string) => s.replace(/\{\{c\d+::(.*?)\}\}/g, "______");
const clozeRevealed = (s: string) => s.replace(/\{\{c\d+::(.*?)\}\}/g, "**$1**");

/** 🎓 Study — adaptive quizzes & flashcards with spaced repetition, generated by the tutor agents. */
export default function Study({ onAsk }: { onAsk: (prompt: string) => void }) {
  const [decks, setDecks] = useState<DeckLite[]>([]);
  const [agents, setAgents] = useState<AgentLite[]>([]);
  const [open, setOpen] = useState<Deck | null>(null);
  const [queue, setQueue] = useState<string[]>([]);
  const [stats, setStats] = useState<Stats | null>(null);
  const [view, setView] = useState<"list" | "deck" | "session">("list");
  const [creating, setCreating] = useState(false);
  const [form, setForm] = useState({ subject: "", scope: "", language: "English", agent: "" });
  const [busy, setBusy] = useState<string | null>(null);
  const [err, setErr] = useState<string | null>(null);

  const load = useCallback(() => fetch("/api/study/decks").then((r) => r.json()).then((j) => { setDecks(j.decks ?? []); setAgents(j.agents ?? []); }).catch(() => undefined), []);
  useEffect(() => { load(); }, [load]);

  const openDeck = async (id: string) => {
    const j = await fetch(`/api/study/decks/${id}`).then((r) => r.json());
    if (j.deck) { setOpen(j.deck); setQueue(j.queue); setStats(j.stats); setView("deck"); }
  };
  const create = async () => {
    if (!form.subject.trim()) return; setBusy("create"); setErr(null);
    const j = await fetch("/api/study/decks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, agent: form.agent || undefined }) }).then((r) => r.json());
    setBusy(null);
    if (j.deck) { setCreating(false); setForm({ subject: "", scope: "", language: "English", agent: "" }); await load(); await openDeck(j.deck.id); await generate(j.deck.id, { count: 12 }); }
    else setErr(j.error ?? "Could not create deck");
  };
  const generate = async (id: string, opts: { count?: number; focus?: string; adaptive?: boolean; kinds?: Kind[] }) => {
    setBusy("generate"); setErr(null);
    const j = await fetch(`/api/study/decks/${id}/generate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(opts) }).then((r) => r.json());
    setBusy(null);
    if (j.error) setErr(j.error); else await openDeck(id);
    load();
  };
  const remove = async (id: string) => { if (!confirm("Delete this deck?")) return; await fetch(`/api/study/decks/${id}`, { method: "DELETE" }); setView("list"); setOpen(null); load(); };

  if (view === "session" && open) return <Session deck={open} queue={queue} onExit={() => { openDeck(open.id); load(); }} onAsk={onAsk} />;

  return (
    <div className="study">
      <div className="gallery-head">
        <div><h2 style={{ margin: 0 }}>🎓 Study</h2><p className="hint" style={{ margin: "4px 0 0", textAlign: "left" }}>Adaptive quizzes and flashcards with spaced repetition — cards are written by the right tutor agent for your subject, and new cards target what you keep missing.</p></div>
        {view === "list" ? <button className="send" onClick={() => setCreating(true)}>+ New deck</button> : <button className="send" onClick={() => { setView("list"); setOpen(null); load(); }}>← All decks</button>}
      </div>
      {err && <div className="err-box">{err}</div>}

      {creating && (
        <div className="gallery-form">
          <input className="agent-search" placeholder="Subject — e.g. Class 12 Physics: Electrostatics, GST for CA Inter, Spanish A2 verbs, OWASP Top 10" value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} autoFocus />
          <textarea className="agent-search" rows={3} placeholder="Scope (optional): paste a syllabus, chapter list, your notes, or the exam you're preparing for" value={form.scope} onChange={(e) => setForm({ ...form, scope: e.target.value })} />
          <div className="row" style={{ gap: 8, flexWrap: "wrap" }}>
            <select className="agent-search" style={{ maxWidth: 200 }} value={form.language} onChange={(e) => setForm({ ...form, language: e.target.value })}>{["English", "Tamil", "Hindi", "Bilingual English + Tamil", "Bilingual English + Hindi", "Spanish", "French", "German", "Japanese"].map((l) => <option key={l}>{l}</option>)}</select>
            <select className="agent-search" style={{ maxWidth: 260 }} value={form.agent} onChange={(e) => setForm({ ...form, agent: e.target.value })}><option value="">Tutor: auto-pick by subject</option>{agents.map((a) => <option key={a.id} value={a.id}>{a.icon} {a.name}</option>)}</select>
            <button className="send" disabled={busy === "create" || !form.subject.trim()} onClick={create}>{busy === "create" ? "Creating…" : "Create & generate 12 cards"}</button>
            <button className="chip" onClick={() => setCreating(false)}>Cancel</button>
          </div>
        </div>
      )}

      {view === "list" && (
        <div className="study-grid">
          {decks.length === 0 && !creating && <div className="empty"><div className="empty-icon">🎓</div><h3>No decks yet</h3><p className="hint">Create one for any subject — school, college, competitive exams, languages, coding, law, finance.</p></div>}
          {decks.map((d) => (
            <button key={d.id} className="study-card" onClick={() => openDeck(d.id)}>
              <div className="row" style={{ justifyContent: "space-between" }}><b>{d.title}</b><span className="meta">{agents.find((a) => a.id === d.agent)?.icon ?? "🎓"} @{d.agent}</span></div>
              <div className="hint" style={{ textAlign: "left", margin: 0 }}>{d.language} · {d.stats.total} cards · {d.stats.learned} learned{d.stats.retention !== null ? ` · ${d.stats.retention}% retention` : ""}</div>
              <StageBar s={d.stats} />
              <div className="row" style={{ justifyContent: "space-between" }}>
                <span className={`chip ${d.stats.due ? "on" : ""}`}>{d.stats.due ? `${d.stats.due} due today` : d.stats.byStage.new ? `${Math.min(10, d.stats.byStage.new)} new to learn` : "All caught up ✓"}</span>
                <Streak history={d.history} />
              </div>
            </button>
          ))}
        </div>
      )}

      {view === "deck" && open && stats && (
        <div className="study-deck">
          <div className="study-summary">
            <div><h3 style={{ margin: 0 }}>{open.title}</h3><div className="hint" style={{ textAlign: "left", margin: "2px 0 0" }}>{open.subject}{open.scope ? ` — ${open.scope.slice(0, 140)}${open.scope.length > 140 ? "…" : ""}` : ""}</div></div>
            <div className="study-kpis">
              <div><b>{stats.total}</b><span>cards</span></div><div><b>{stats.due}</b><span>due</span></div><div><b>{stats.byStage.new}</b><span>new</span></div><div><b>{stats.byStage.mature}</b><span>mature</span></div><div><b>{stats.retention ?? "—"}{stats.retention !== null ? "%" : ""}</b><span>retention</span></div>
            </div>
            <StageBar s={stats} />
            <div className="row" style={{ gap: 8, flexWrap: "wrap" }}>
              <button className="send" disabled={!queue.length} onClick={() => setView("session")}>{queue.length ? `Start session (${queue.length})` : "Nothing due — generate more or come back tomorrow"}</button>
              <button className="chip" disabled={busy === "generate"} onClick={() => generate(open.id, { count: 12 })}>{busy === "generate" ? "Generating…" : "+12 cards"}</button>
              <button className="chip" disabled={busy === "generate"} onClick={() => generate(open.id, { count: 10, adaptive: true })} title="Targets cards you keep failing">+10 adaptive</button>
              <button className="chip" disabled={busy === "generate"} onClick={() => generate(open.id, { count: 10, kinds: ["mcq"] })}>+10 MCQ (exam style)</button>
              <button className="chip" onClick={() => { const f = prompt("Focus this batch on (topic, chapter, weakness):"); if (f) generate(open.id, { count: 10, focus: f }); }}>+ focused…</button>
              <button className="chip" onClick={() => onAsk(`@${open.agent} I'm studying "${open.subject}"${open.scope ? ` (${open.scope.slice(0, 200)})` : ""}. Explain the 5 most important ideas I must understand before a test, with one worked example each.`)}>Ask the tutor</button>
              <button className="chip" onClick={() => remove(open.id)} style={{ marginLeft: "auto" }}>Delete deck</button>
            </div>
          </div>
          <Heatmap history={open.history} />
          <div className="study-cards">
            {open.cards.map((c) => (
              <div key={c.id} className={`study-row stage-${stageOf(c.srs)}`}>
                <span className="meta">{KIND_LABEL[c.kind]} · d{c.difficulty}</span>
                <div className="study-row-main"><div dangerouslySetInnerHTML={{ __html: renderMarkdown(c.kind === "cloze" ? clozeRevealed(c.front) : c.front) }} />{c.kind !== "cloze" && <div className="hint" style={{ textAlign: "left", margin: 0 }}>→ {c.back}</div>}</div>
                <span className="meta" title={`ease ${c.srs.ease} · interval ${c.srs.interval}d · lapses ${c.srs.lapses}`}>{stageOf(c.srs)}{c.srs.lapses ? ` · ${c.srs.lapses}✗` : ""}</span>
                <button className="link" onClick={async () => { await fetch(`/api/study/decks/${open.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ deleteCard: c.id }) }); openDeck(open.id); }}>remove</button>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function stageOf(s: Srs): "new" | "learning" | "young" | "mature" { if (s.reps === 0 && !s.lastReviewed) return "new"; if (s.interval < 1) return "learning"; return s.interval < 21 ? "young" : "mature"; }

function StageBar({ s }: { s: Stats }) {
  const t = Math.max(1, s.total); const seg = (n: number) => ({ width: `${(n / t) * 100}%` });
  return <div className="stagebar" title={`new ${s.byStage.new} · learning ${s.byStage.learning} · young ${s.byStage.young} · mature ${s.byStage.mature}`}><i className="st-new" style={seg(s.byStage.new)} /><i className="st-learning" style={seg(s.byStage.learning)} /><i className="st-young" style={seg(s.byStage.young)} /><i className="st-mature" style={seg(s.byStage.mature)} /></div>;
}
function Streak({ history }: { history: { at: number }[] }) {
  const days = new Set(history.map((h) => h.at)); let n = 0; const d = new Date(); d.setHours(0, 0, 0, 0);
  for (;;) { if (days.has(d.getTime())) { n++; d.setDate(d.getDate() - 1); } else break; }
  return <span className="meta">{n ? `🔥 ${n}-day streak` : ""}</span>;
}
function Heatmap({ history }: { history: { at: number; reviewed: number; correct: number }[] }) {
  const map = new Map(history.map((h) => [h.at, h])); const cells = []; const d = new Date(); d.setHours(0, 0, 0, 0);
  for (let i = 55; i >= 0; i--) { const t = d.getTime() - i * 86_400_000; const h = map.get(t); cells.push(<i key={t} className={`hm ${h ? (h.reviewed >= 20 ? "hm3" : h.reviewed >= 8 ? "hm2" : "hm1") : ""}`} title={`${new Date(t).toDateString()}: ${h ? `${h.reviewed} reviewed, ${h.correct} correct` : "—"}`} />); }
  return <div className="heatmap">{cells}</div>;
}

/** One review session over the queue. */
function Session({ deck, queue, onExit, onAsk }: { deck: Deck; queue: string[]; onExit: () => void; onAsk: (p: string) => void }) {
  const cards = useMemo(() => queue.map((id) => deck.cards.find((c) => c.id === id)!).filter(Boolean), [deck, queue]);
  const [i, setI] = useState(0);
  const [revealed, setRevealed] = useState(false);
  const [answer, setAnswer] = useState("");
  const [result, setResult] = useState<{ correct: boolean; feedback: string } | null>(null);
  const [score, setScore] = useState({ done: 0, correct: 0 });
  const [busy, setBusy] = useState(false);
  const c = cards[i];
  const next = () => { setI((x) => x + 1); setRevealed(false); setAnswer(""); setResult(null); };
  const grade = async (g: 0 | 1 | 2 | 3) => { await fetch(`/api/study/decks/${deck.id}/review`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ cardId: c.id, grade: g }) }); setScore((s) => ({ done: s.done + 1, correct: s.correct + (g > 0 ? 1 : 0) })); next(); };
  const submit = async (a: string) => {
    setBusy(true);
    const j = await fetch(`/api/study/decks/${deck.id}/quiz`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ cardId: c.id, answer: a }) }).then((r) => r.json());
    setBusy(false); setResult(j.error ? { correct: false, feedback: j.error } : j); setRevealed(true);
    if (!j.error) setScore((s) => ({ done: s.done + 1, correct: s.correct + (j.correct ? 1 : 0) }));
  };
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => { if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return; if (!c) return; if (e.key === " " && !revealed && c.kind === "flashcard") { e.preventDefault(); setRevealed(true); } if (revealed && c.kind === "flashcard" && ["1", "2", "3", "4"].includes(e.key)) grade((Number(e.key) - 1) as 0 | 1 | 2 | 3); };
    window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [c, revealed]);

  if (!c) return (
    <div className="study"><div className="empty"><div className="empty-icon">🎉</div><h3>Session complete</h3><p className="hint">{score.correct}/{score.done} correct. Cards you missed come back in 10 minutes; the rest are scheduled by how well you knew them.</p>
      <div className="row" style={{ justifyContent: "center", gap: 8 }}><button className="send" onClick={onExit}>Back to deck</button><button className="chip" onClick={() => onAsk(`@${deck.agent} I just did a study session on "${deck.subject}" and got ${score.correct}/${score.done}. Quiz me orally on the hardest ideas, one question at a time, and correct me gently.`)}>Continue with the tutor in chat</button></div></div></div>
  );
  const pct = Math.round((i / cards.length) * 100);
  return (
    <div className="study">
      <div className="row" style={{ justifyContent: "space-between" }}><button className="chip" onClick={onExit}>← End session</button><span className="meta">{i + 1} / {cards.length} · {score.correct}/{score.done} correct</span></div>
      <div className="progress"><i style={{ width: `${pct}%` }} /></div>
      <div className="study-stage">
        <span className="meta">{KIND_LABEL[c.kind]} · {c.tags.slice(0, 3).map((t) => `#${t}`).join(" ")}</span>
        <div className="study-q" dangerouslySetInnerHTML={{ __html: renderMarkdown(c.kind === "cloze" ? (revealed ? clozeRevealed(c.front) : clozeFront(c.front)) : c.front) }} />

        {c.kind === "mcq" && !revealed && <div className="study-options">{c.options!.map((o) => <button key={o} className="study-opt" disabled={busy} onClick={() => submit(o)}>{o}</button>)}</div>}
        {c.kind === "mcq" && revealed && <div className="study-options">{c.options!.map((o) => <div key={o} className={`study-opt ${o === c.back ? "ok" : answer === o ? "bad" : ""}`}>{o}</div>)}</div>}

        {(c.kind === "cloze" || c.kind === "short") && !revealed && (
          <form className="row" style={{ gap: 8 }} onSubmit={(e) => { e.preventDefault(); if (answer.trim()) submit(answer.trim()); }}>
            <input className="agent-search" placeholder="Type your answer…" value={answer} onChange={(e) => setAnswer(e.target.value)} autoFocus />
            <button className="send" disabled={busy || !answer.trim()}>{busy ? "Checking…" : "Check"}</button>
            <button type="button" className="chip" onClick={() => { setRevealed(true); setResult({ correct: false, feedback: `Answer: ${c.back}` }); setScore((s) => ({ done: s.done + 1, correct: s.correct })); fetch(`/api/study/decks/${deck.id}/review`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ cardId: c.id, grade: 0 }) }); }}>Don't know</button>
          </form>
        )}

        {c.kind === "flashcard" && !revealed && <button className="send" onClick={() => setRevealed(true)}>Show answer <kbd>space</kbd></button>}
        {c.kind === "flashcard" && revealed && (
          <>
            <div className="study-a bubble" dangerouslySetInnerHTML={{ __html: renderMarkdown(c.back) }} />
            {c.explanation && <div className="hint" style={{ textAlign: "left" }}>{c.explanation}</div>}
            <div className="study-grades">
              <button className="chip g0" onClick={() => grade(0)}>Again <kbd>1</kbd><small>10 min</small></button>
              <button className="chip g1" onClick={() => grade(1)}>Hard <kbd>2</kbd><small>{nextIn(c.srs, 1)}</small></button>
              <button className="chip g2" onClick={() => grade(2)}>Good <kbd>3</kbd><small>{nextIn(c.srs, 2)}</small></button>
              <button className="chip g3" onClick={() => grade(3)}>Easy <kbd>4</kbd><small>{nextIn(c.srs, 3)}</small></button>
            </div>
          </>
        )}

        {result && c.kind !== "flashcard" && (
          <>
            <div className={`study-result ${result.correct ? "ok" : "bad"}`}>{result.correct ? "✓ Correct" : "✗ Not quite"} — {result.feedback}</div>
            {c.explanation && <div className="hint" style={{ textAlign: "left" }}>{c.explanation}</div>}
            <div className="row" style={{ gap: 8 }}><button className="send" onClick={next} autoFocus>Next →</button><button className="chip" onClick={() => onAsk(`@${deck.agent} Explain this to me properly, I got it wrong:\n\nQ: ${c.kind === "cloze" ? clozeRevealed(c.front) : c.front}\nA: ${c.back}`)}>Explain in chat</button></div>
          </>
        )}
      </div>
    </div>
  );
}

/** Preview of the next interval for a grade (mirrors srs.review without importing server code). */
function nextIn(s: Srs, g: 1 | 2 | 3): string {
  let ease = Math.max(1.3, s.ease + (g === 1 ? -0.15 : g === 3 ? 0.15 : 0)); let iv: number;
  if (s.reps === 0) iv = g === 3 ? 4 : 1; else if (s.reps === 1) iv = g === 1 ? 3 : g === 2 ? 6 : 10; else iv = Math.round(s.interval * ease * (g === 1 ? 1.2 / ease : g === 3 ? 1.3 : 1));
  iv = Math.max(1, Math.min(iv, 365));
  return iv >= 30 ? `${Math.round(iv / 30)} mo` : `${iv} d`;
}
