"""QR code generation — a complete encoder in the standard library.

QR is one of those formats everyone assumes needs a dependency. It doesn't:
the whole pipeline — byte-mode encoding, Reed–Solomon error correction over
GF(256), mask selection by penalty scoring, and module layout — is implemented
here in pure Python and rendered onto a :class:`~aetheris.media.canvas.Canvas`
so the code inherits the studio's palette system, deterministic seeding, and
PNG encoder.

Honest limits, stated up front:

* **Byte mode only** (UTF-8). No numeric/alphanumeric compaction, no kanji.
* **Versions 1–10** (21×21 up to 57×57 modules), so payloads are capped at
  roughly 119 bytes at ECC level L up to ~70 bytes at level H. Enough for
  URLs, Wi-Fi strings, vCards, and short text — the QR sweet spot.
* **ECC levels L/M/Q/H** with the full ISO mask-and-penalty selection, so the
  output is scannable by real readers, not just decorative.

The result is a real, scannable QR code — stylable with foreground/background
colours, a quiet zone, rounded finder corners, and an optional centre letter —
produced offline and deterministically (no seed randomness is involved; the
same input always yields the same matrix).
"""

from __future__ import annotations

from dataclasses import dataclass

from .canvas import Canvas, hex_to_rgb

# --- GF(256) arithmetic --------------------------------------------------------
# The field is generated by x^8 + x^4 + x^3 + x^2 + 1 (0x11D), the QR standard.

_GF_EXP = [0] * 512
_GF_LOG = [0] * 256

_value = 1
for _i in range(255):
    _GF_EXP[_i] = _value
    _GF_LOG[_value] = _i
    _value <<= 1
    if _value & 0x100:
        _value ^= 0x11D
for _i in range(255, 512):
    _GF_EXP[_i] = _GF_EXP[_i - 255]


def _gf_mul(a: int, b: int) -> int:
    if a == 0 or b == 0:
        return 0
    return _GF_EXP[_GF_LOG[a] + _GF_LOG[b]]


# Full ISO/IEC 18004 block table for versions 1–10.
# Each entry: {level: (ec_per_block, [(num_blocks, data_codewords), ...])}
_BLOCKS: dict[int, dict[str, tuple[int, list[tuple[int, int]]]]] = {
    1: {"L": (7, [(1, 19)]), "M": (10, [(1, 16)]), "Q": (13, [(1, 13)]), "H": (17, [(1, 9)])},
    2: {"L": (10, [(1, 34)]), "M": (16, [(1, 28)]), "Q": (22, [(1, 22)]), "H": (28, [(1, 16)])},
    3: {"L": (15, [(1, 55)]), "M": (26, [(1, 44)]), "Q": (18, [(2, 17)]), "H": (22, [(2, 13)])},
    4: {"L": (20, [(1, 80)]), "M": (18, [(2, 32)]), "Q": (26, [(2, 24)]), "H": (16, [(4, 9)])},
    5: {"L": (26, [(1, 108)]), "M": (24, [(2, 43)]), "Q": (18, [(2, 15), (2, 16)]), "H": (22, [(2, 11), (2, 12)])},
    6: {"L": (18, [(2, 68)]), "M": (16, [(4, 27)]), "Q": (24, [(4, 19)]), "H": (28, [(4, 15)])},
    7: {"L": (20, [(2, 78)]), "M": (18, [(4, 31)]), "Q": (18, [(2, 14), (4, 15)]), "H": (26, [(4, 13), (1, 14)])},
    8: {"L": (24, [(2, 97)]), "M": (22, [(2, 38), (2, 39)]), "Q": (22, [(4, 18), (2, 19)]), "H": (26, [(4, 14), (2, 15)])},
    9: {"L": (30, [(2, 116)]), "M": (22, [(3, 36), (2, 37)]), "Q": (20, [(4, 16), (4, 17)]), "H": (24, [(4, 12), (4, 13)])},
    10: {"L": (18, [(2, 68), (2, 69)]), "M": (26, [(4, 43), (1, 44)]), "Q": (24, [(6, 19), (2, 20)]), "H": (28, [(6, 15), (2, 16)])},
}

# Alignment pattern centres per version.
_ALIGNMENT: dict[int, list[int]] = {
    1: [], 2: [6, 18], 3: [6, 22], 4: [6, 26], 5: [6, 30], 6: [6, 34],
    7: [6, 22, 38], 8: [6, 24, 42], 9: [6, 26, 46], 10: [6, 28, 50],
}

# Format information: (data_bits << 10) | BCH(15,5) remainder, XORed with 0x5412.
_FORMAT_INFO: list[int] = []
for _fmt_data in range(32):
    _value = _fmt_data << 10
    _remainder = _value
    _poly = 0x537
    for _bit in range(14, 9, -1):
        if _remainder & (1 << _bit):
            _remainder ^= _poly << (_bit - 10)
    _FORMAT_INFO.append(((_fmt_data << 10) | _remainder) ^ 0x5412)

# Version information (versions ≥ 7): 18-bit BCH.
_VERSION_INFO: dict[int, int] = {}
for _version in range(7, 11):
    _value = _version << 12
    _remainder = _value
    _poly = 0x1F25
    for _bit in range(17, 11, -1):
        if _remainder & (1 << _bit):
            _remainder ^= _poly << (_bit - 12)
    _VERSION_INFO[_version] = _value | _remainder


@dataclass
class QRPlan:
    """An encoded QR matrix ready for rendering."""

    matrix: list[list[bool]]
    version: int
    ecl: str
    payload: str
    mask: int
    size: int

    @property
    def capacity_bytes(self) -> int:
        ec_per_block, groups = _BLOCKS[self.version][self.ecl]
        return sum(count * data for count, data in groups)


# --- Reed–Solomon ---------------------------------------------------------------

def _rs_generator(degree: int) -> list[int]:
    """Generator polynomial for ``degree`` EC codewords."""
    gen = [1]
    for i in range(degree):
        factor = _GF_EXP[i]
        new = [0] * (len(gen) + 1)
        for j, coefficient in enumerate(gen):
            new[j] ^= _gf_mul(coefficient, factor)
            new[j + 1] ^= coefficient
        gen = new
    return gen


def _rs_encode(data: list[int], ec_count: int) -> list[int]:
    """Append ``ec_count`` Reed–Solomon error-correction codewords."""
    gen = _rs_generator(ec_count)
    remainder = [0] * ec_count
    for byte in data:
        factor = byte ^ remainder.pop(0)
        remainder.append(0)
        for i in range(ec_count):
            remainder[i] ^= _gf_mul(gen[i], factor)
    return list(data) + remainder


# --- Matrix construction ---------------------------------------------------------

def _encode(data: bytes, ecl: str, version: int) -> tuple[list[int], int]:
    """Produce the full interleaved codeword stream (data + EC)."""
    ec_per_block, groups = _BLOCKS[version][ecl]
    bits: list[int] = []
    for byte in data:
        bits.extend((byte >> shift) & 1 for shift in range(7, -1, -1))
    bits.extend([0, 0, 0, 0])  # terminator

    capacity_bits = sum(count * d * 8 for count, d in groups)
    if len(bits) > capacity_bits:
        raise ValueError(
            f"Payload too large for version {version}-{ecl.upper()} "
            f"({capacity_bits // 8} bytes max)."
        )
    # Pad to a byte boundary, then alternate pad codewords 0xEC / 0x11.
    while len(bits) % 8:
        bits.append(0)
    pad_byte = 0xEC
    while len(bits) < capacity_bits:
        bits.extend((pad_byte >> shift) & 1 for shift in range(7, -1, -1))
        pad_byte ^= 0xEC ^ 0x11

    codewords: list[int] = []
    for i in range(0, len(bits), 8):
        byte = 0
        for bit in bits[i : i + 8]:
            byte = (byte << 1) | bit
        codewords.append(byte)

    # Split into blocks, RS-encode each, then interleave data and EC.
    blocks: list[list[int]] = []
    position = 0
    for count, data_words in groups:
        for _ in range(count):
            block = codewords[position : position + data_words]
            position += data_words
            blocks.append(_rs_encode(block, ec_per_block))

    interleaved: list[int] = []
    max_data = max(len(b) - ec_per_block for b in blocks)
    for i in range(max_data):
        for block in blocks:
            if i < len(block) - ec_per_block:
                interleaved.append(block[i])
    for i in range(ec_per_block):
        for block in blocks:
            interleaved.append(block[len(block) - ec_per_block + i])
    return interleaved, len(interleaved)


def _place_reserved(matrix: list[list[bool]], reserved: list[list[bool]], size: int, version: int) -> None:
    """Draw function patterns and mark every reserved module position."""
    for row, col in ((0, 0), (0, size - 7), (size - 7, 0)):
        for dy in range(7):
            for dx in range(7):
                # Distance 0–1 (centre + inner ring) and 3 (outer ring) are
                # dark; distance 2 is the light ring between them.
                distance = max(abs(dx - 3), abs(dy - 3))
                matrix[row + dy][col + dx] = distance != 2
                reserved[row + dy][col + dx] = True
        # Separators (light ring around the finder).
        for i in range(-1, 8):
            for j in range(-1, 8):
                if not (0 <= row + i < size and 0 <= col + j < size):
                    continue
                if (i in (-1, 7) and -1 <= j <= 7) or (j in (-1, 7) and -1 <= i <= 7):
                    matrix[row + i][col + j] = False
                    reserved[row + i][col + j] = True

    for i in range(8, size - 8):
        matrix[6][i] = matrix[i][6] = i % 2 == 0
        reserved[6][i] = reserved[i][6] = True

    centres = _ALIGNMENT[version]
    for row in centres:
        for col in centres:
            if (row, col) in ((6, 6), (6, size - 7), (size - 7, 6)):
                continue
            for dy in range(-2, 3):
                for dx in range(-2, 3):
                    matrix[row + dy][col + dx] = max(abs(dx), abs(dy)) != 2
                    reserved[row + dy][col + dx] = True

    matrix[size - 8][8] = True  # dark module
    reserved[size - 8][8] = True


def _mask_condition(mask: int, row: int, col: int) -> bool:
    if mask == 0:
        return (row + col) % 2 == 0
    if mask == 1:
        return row % 2 == 0
    if mask == 2:
        return col % 3 == 0
    if mask == 3:
        return (row + col) % 3 == 0
    if mask == 4:
        return (row // 2 + col // 3) % 2 == 0
    if mask == 5:
        return (row * col) % 2 + (row * col) % 3 == 0
    if mask == 6:
        return ((row * col) % 2 + (row * col) % 3) % 2 == 0
    return ((row + col) % 2 + (row * col) % 3) % 2 == 0


def _penalty(matrix: list[list[bool]], size: int) -> int:
    """ISO penalty score: runs, 2×2 blocks, finder-like patterns, imbalance."""
    score = 0
    # Rule 1: runs of 5+ same-colour modules in rows and columns.
    for row in range(size):
        run_colour, run_length = matrix[row][0], 1
        for col in range(1, size):
            if matrix[row][col] == run_colour:
                run_length += 1
            else:
                if run_length >= 5:
                    score += 3 + (run_length - 5)
                run_colour, run_length = matrix[row][col], 1
        if run_length >= 5:
            score += 3 + (run_length - 5)
    for col in range(size):
        run_colour, run_length = matrix[0][col], 1
        for row in range(1, size):
            if matrix[row][col] == run_colour:
                run_length += 1
            else:
                if run_length >= 5:
                    score += 3 + (run_length - 5)
                run_colour, run_length = matrix[row][col], 1
        if run_length >= 5:
            score += 3 + (run_length - 5)

    # Rule 2: 2×2 blocks of identical colour.
    for row in range(size - 1):
        for col in range(size - 1):
            cell = matrix[row][col]
            if (matrix[row][col + 1] == cell and matrix[row + 1][col] == cell
                    and matrix[row + 1][col + 1] == cell):
                score += 3

    # Rule 3: finder-like 1:1:3:1:1 sequences (light:dark:light:dark:light).
    dark = (True, False, True, True, True, False, True)
    light = (False, True, False, False, False, True, False)
    for row in range(size):
        for col in range(size - 6):
            window = tuple(matrix[row][col + i] for i in range(7))
            if window == dark or window == light:
                score += 40
    for col in range(size):
        for row in range(size - 6):
            window = tuple(matrix[row + i][col] for i in range(7))
            if window == dark or window == light:
                score += 40

    # Rule 4: dark-module proportion.
    dark_count = sum(sum(1 for cell in row if cell) for row in matrix)
    proportion = dark_count * 100 // (size * size)
    previous = proportion // 5 * 5
    score += min(abs(previous - 50) // 5, abs(previous + 5 - 50) // 5) * 10
    return score


def _format_bits(ecl: str, mask: int) -> int:
    ecl_index = {"L": 1, "M": 0, "Q": 3, "H": 2}[ecl]
    return _FORMAT_INFO[(ecl_index << 3) | mask]


def _draw_format(matrix: list[list[bool]], reserved: list[list[bool]], size: int, format_value: int) -> None:
    bits = [(format_value >> i) & 1 for i in range(14, -1, -1)]
    positions = (
        [(8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 7), (8, 8),
         (7, 8), (5, 8), (4, 8), (3, 8), (2, 8), (1, 8), (0, 8)]
        + [(size - 1, 8), (size - 2, 8), (size - 3, 8), (size - 4, 8),
           (size - 5, 8), (size - 6, 8), (size - 7, 8), (8, size - 8),
           (8, size - 7), (8, size - 6), (8, size - 5), (8, size - 4),
           (8, size - 3), (8, size - 2), (8, size - 1)]
    )
    for (row, col), bit in zip(positions, bits):
        matrix[row][col] = bool(bit)
        reserved[row][col] = True


def _draw_version(matrix: list[list[bool]], reserved: list[list[bool]], size: int, version: int) -> None:
    if version < 7:
        return
    value = _VERSION_INFO[version]
    bits = [(value >> i) & 1 for i in range(17, -1, -1)]
    for i in range(18):
        row, col = i // 3, size - 11 + i % 3
        matrix[row][col] = bool(bits[i])
        matrix[col][row] = bool(bits[i])
        reserved[row][col] = reserved[col][row] = True


def _build_matrix(payload: bytes, ecl: str, version: int, mask: int) -> list[list[bool]]:
    size = 17 + 4 * version
    matrix = [[False] * size for _ in range(size)]
    reserved = [[False] * size for _ in range(size)]
    _place_reserved(matrix, reserved, size, version)
    _draw_format(matrix, reserved, size, _format_bits(ecl, mask))
    _draw_version(matrix, reserved, size, version)

    codewords, _ = _encode(payload, ecl, version)
    bit_index = 0
    total_bits = len(codewords) * 8
    col = size - 1
    upward = True
    while col > 0:
        if col == 6:  # skip the vertical timing column
            col -= 1
        for row in range(size - 1, -1, -1) if upward else range(size):
            for dx in (0, 1):
                c = col - dx
                if c < 0:
                    continue
                if reserved[row][c]:
                    continue
                if bit_index < total_bits:
                    bit = (codewords[bit_index // 8] >> (7 - bit_index % 8)) & 1
                    matrix[row][c] = bool(bit) ^ _mask_condition(mask, row, c)
                    bit_index += 1
        upward = not upward
        col -= 2
    return matrix


def encode(data: str, *, ecl: str = "M", version: int | None = None, mask: int | None = None) -> QRPlan:
    """Encode ``data`` into a QR plan with optimal version and mask.

    ``ecl`` is the error-correction level (``L``, ``M``, ``Q``, ``H``); the
    version is chosen automatically unless pinned, and the mask is chosen by
    ISO penalty scoring unless pinned.
    """
    ecl = (ecl or "M").upper()
    if ecl not in _BLOCKS[1]:
        raise ValueError(f"Unknown ECC level '{ecl}'. Choose L, M, Q, or H.")
    payload = data.encode("utf-8")

    def _capacity(v: int) -> int:
        ec_per_block, groups = _BLOCKS[v][ecl]
        return sum(count * words for count, words in groups)

    if version is None:
        # +2: length header is 1 byte up to v9, 2 bytes at v10; keep a margin.
        version = next((v for v in range(1, 11) if len(payload) + 2 <= _capacity(v)), None)
        if version is None:
            raise ValueError(
                f"Payload is {len(payload)} bytes; version 10-{ecl} holds at most "
                f"{_capacity(10) - 2}. Shorten the content or lower the ECC level."
            )
    elif not 1 <= version <= 10:
        raise ValueError("QR version must be 1–10.")

    if mask is None:
        best_mask, best_penalty = 0, None
        for candidate in range(8):
            matrix = _build_matrix(payload, ecl, version, candidate)
            score = _penalty(matrix, len(matrix))
            if best_penalty is None or score < best_penalty:
                best_mask, best_penalty = candidate, score
        mask = best_mask

    matrix = _build_matrix(payload, ecl, version, mask)
    return QRPlan(matrix=matrix, version=version, ecl=ecl, payload=data, mask=mask, size=len(matrix))


# --- Rendering -------------------------------------------------------------------

def render(
    plan: QRPlan,
    *,
    width: int = 420,
    foreground: str = "#0b132b",
    background: str = "#f8f9fa",
    quiet: int = 4,
    rounded: bool = False,
    letter: str = "",
    letter_color: str | None = None,
) -> Canvas:
    """Draw a QR plan onto a Canvas at ``width`` pixels.

    ``quiet`` is the quiet-zone width in modules; ``rounded`` softens the
    finder eyes and module corners; ``letter`` places a single character in
    the centre (drawn over a cleared module block so scannability survives).
    """
    foreground = hex_to_rgb(foreground)
    background = hex_to_rgb(background)
    if letter_color is None:
        letter_color = foreground

    size = plan.size
    modules = size + 2 * quiet
    module = max(2, width // modules)
    width = module * modules
    canvas = Canvas(width, width, background)

    # Scale factor for coarse, chunky pixel-art styling.
    from .font import glyph, text_width

    for row in range(size):
        for col in range(size):
            if not plan.matrix[row][col]:
                continue
            x = (col + quiet) * module
            y = (row + quiet) * module
            if rounded:
                inset = max(1, module // 4)
                canvas.rect(x + inset, y, module - 2 * inset, module, foreground)
                canvas.rect(x, y + inset, module, module - 2 * inset, foreground)
                canvas.rect(x + inset, y + inset, module - 2 * inset,
                            module - 2 * inset, foreground)
            else:
                canvas.rect(x, y, module, module, foreground)

    # Optional centre letter: clear a 5×5-module block and draw the glyph.
    if letter:
        letter = letter[:1].upper()
        clear_span = 5
        centre = size // 2
        for row in range(centre - clear_span // 2, centre + clear_span // 2 + 1):
            for col in range(centre - clear_span // 2, centre + clear_span // 2 + 1):
                x = (col + quiet) * module
                y = (row + quiet) * module
                canvas.rect(x, y, module, module, background)
        scale = max(2, module * clear_span // 6)
        pattern = glyph(letter)
        gw = text_width(letter, scale)
        x = (width - gw) // 2
        y = (width - 8 * scale) // 2
        for dy, line in enumerate(pattern):
            for dx, cell in enumerate(line):
                if cell:
                    canvas.rect(x + dx * scale, y + dy * scale, scale, scale, letter_color)

    return canvas


def generate(
    data: str,
    *,
    ecl: str = "M",
    version: int | None = None,
    width: int = 420,
    foreground: str = "#0b132b",
    background: str = "#f8f9fa",
    quiet: int = 4,
    rounded: bool = False,
    letter: str = "",
) -> tuple[bytes, dict]:
    """Encode ``data`` as a styled QR code PNG. Returns ``(png_bytes, meta)``."""
    plan = encode(data, ecl=ecl, version=version)
    canvas = render(
        plan, width=width, foreground=foreground, background=background,
        quiet=quiet, rounded=rounded, letter=letter,
    )
    meta = {
        "version": plan.version,
        "ecc": plan.ecl,
        "mask": plan.mask,
        "modules": plan.size,
        "capacity_bytes": plan.capacity_bytes,
        "payload_bytes": len(plan.payload.encode("utf-8")),
        "width": canvas.width,
        "height": canvas.height,
    }
    return canvas.to_png(), meta


__all__ = ["QRPlan", "encode", "render", "generate"]
